name: hquplink

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.1.0
  built_value: ^6.3.0
  uuid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.2.0
  built_value_generator: ^6.3.0
  swlegion:

dependency_overrides:
  swlegion:
    path: ../swlegion

flutter:
  uses-material-design: true

  assets:
    - assets/cards/commands/
    - assets/cards/units/
    - assets/cards/upgrades/
    - assets/dice/attack/
    - assets/dice/defense/
