targets:
  $default:
    sources:
      - "cards/**/*.png"
      - "tool/**"
    builders:
      swlegion_assets|_generate_thumbs:
        enabled: true

builders:
  _generate_thumbs:
    import: tool/src/generate_thumbnails.dart
    builder_factories:
      - generateThumbnails
    build_extensions:
      ".png":
        - ".thumb.png"
    build_to: source
    auto_apply: root_package
